name 'module10'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'All Rights Reserved'
description 'Installs/Configures module10'
long_description 'Installs/Configures module10'
version '0.1.4'
chef_version '>= 13.0'
depends 'docker', '~> 4.9.2'
