version: '2'

services:
  collectd1:
    container_name: collectd1
    image: fr3nd/collectd
    privileged: true
    network_mode: host
    volumes:
      - /proc:/mnt/proc:ro
      - ./collectd.conf:/etc/collectd/collectd.conf

  collectd2:
    container_name: collectd2
    image: fr3nd/collectd
    privileged: true
    hostname: collectd-itself
    volumes:
      - ./collectd-itself.conf:/etc/collectd/collectd.conf

  influxdb:
    container_name: influxdb
    image: influxdb:1.0
    ports:
      - "8083:8083"
      - "8086:8086"
      - "25826:25826/udp"
    volumes:
      - /var/lib/influxdb
      - ./influxdb.conf:/etc/influxdb/influxdb.conf
      - ./types.db:/usr/share/collectd/types.db:ro

  grafana:
    container_name: grafana
    image: grafana/grafana:5.4.3
    ports:
      - "3000:3000"
    volumes:
      - /var/lib/grafana
