version: '2.2'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.6.1
    container_name: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    restart: unless-stopped
    ports:
      - 9200:9200
      - 9300:9300
  
  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    container_name: logstash
    restart: unless-stopped
    ports:
      - 5044:5044
  
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.6.1
    container_name: kibana
    ports:
      - 5601:5601
    command: bash -c "sleep 30; /usr/share/kibana/bin/../node/bin/node --no-warnings --max-http-header-size=65536 /usr/share/kibana/bin/../src/cli --cpu.cgroup.path.override=/ --cpuacct.cgroup.path.override=/" 

  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    ports:
      - 80:80
    container_name: filebeat
    restart: unless-stopped
